//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace NSE.Lib.Abara.com.abarasoftware.testblinkws.TU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransUnionWSSoap", Namespace="http://blinkws.abarasoftware.com.TU")]
    public partial class TransUnionWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestConnectivityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExistingReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransUnionWS() {
            this.Url = global::NSE.Lib.Abara.Properties.Settings.Default.NSE_Lib_Abara_com_abarasoftware_testblinkws_TU_TransUnionWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestConnectivityCompletedEventHandler TestConnectivityCompleted;
        
        /// <remarks/>
        public event GetNewReportCompletedEventHandler GetNewReportCompleted;
        
        /// <remarks/>
        public event GetExistingReportCompletedEventHandler GetExistingReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://blinkws.abarasoftware.com.TU/TestConnectivity", RequestNamespace="http://blinkws.abarasoftware.com.TU", ResponseNamespace="http://blinkws.abarasoftware.com.TU", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestConnectivity(string BLink_login, string BLink_pwd) {
            object[] results = this.Invoke("TestConnectivity", new object[] {
                        BLink_login,
                        BLink_pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestConnectivityAsync(string BLink_login, string BLink_pwd) {
            this.TestConnectivityAsync(BLink_login, BLink_pwd, null);
        }
        
        /// <remarks/>
        public void TestConnectivityAsync(string BLink_login, string BLink_pwd, object userState) {
            if ((this.TestConnectivityOperationCompleted == null)) {
                this.TestConnectivityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectivityOperationCompleted);
            }
            this.InvokeAsync("TestConnectivity", new object[] {
                        BLink_login,
                        BLink_pwd}, this.TestConnectivityOperationCompleted, userState);
        }
        
        private void OnTestConnectivityOperationCompleted(object arg) {
            if ((this.TestConnectivityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectivityCompleted(this, new TestConnectivityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://blinkws.abarasoftware.com.TU/GetNewReport", RequestNamespace="http://blinkws.abarasoftware.com.TU", ResponseNamespace="http://blinkws.abarasoftware.com.TU", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReportResponse GetNewReport(string BLink_login, string BLink_pwd, InputData reportInput, Services service) {
            object[] results = this.Invoke("GetNewReport", new object[] {
                        BLink_login,
                        BLink_pwd,
                        reportInput,
                        service});
            return ((ReportResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewReportAsync(string BLink_login, string BLink_pwd, InputData reportInput, Services service) {
            this.GetNewReportAsync(BLink_login, BLink_pwd, reportInput, service, null);
        }
        
        /// <remarks/>
        public void GetNewReportAsync(string BLink_login, string BLink_pwd, InputData reportInput, Services service, object userState) {
            if ((this.GetNewReportOperationCompleted == null)) {
                this.GetNewReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewReportOperationCompleted);
            }
            this.InvokeAsync("GetNewReport", new object[] {
                        BLink_login,
                        BLink_pwd,
                        reportInput,
                        service}, this.GetNewReportOperationCompleted, userState);
        }
        
        private void OnGetNewReportOperationCompleted(object arg) {
            if ((this.GetNewReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewReportCompleted(this, new GetNewReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://blinkws.abarasoftware.com.TU/GetExistingReport", RequestNamespace="http://blinkws.abarasoftware.com.TU", ResponseNamespace="http://blinkws.abarasoftware.com.TU", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReportResponse GetExistingReport(System.Guid reportGuid, string BLink_login, string BLink_pwd, Services service) {
            object[] results = this.Invoke("GetExistingReport", new object[] {
                        reportGuid,
                        BLink_login,
                        BLink_pwd,
                        service});
            return ((ReportResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetExistingReportAsync(System.Guid reportGuid, string BLink_login, string BLink_pwd, Services service) {
            this.GetExistingReportAsync(reportGuid, BLink_login, BLink_pwd, service, null);
        }
        
        /// <remarks/>
        public void GetExistingReportAsync(System.Guid reportGuid, string BLink_login, string BLink_pwd, Services service, object userState) {
            if ((this.GetExistingReportOperationCompleted == null)) {
                this.GetExistingReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExistingReportOperationCompleted);
            }
            this.InvokeAsync("GetExistingReport", new object[] {
                        reportGuid,
                        BLink_login,
                        BLink_pwd,
                        service}, this.GetExistingReportOperationCompleted, userState);
        }
        
        private void OnGetExistingReportOperationCompleted(object arg) {
            if ((this.GetExistingReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExistingReportCompleted(this, new GetExistingReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public partial class InputData {
        
        private string countryCodeField;
        
        private PhoneTypes phoneTypeField;
        
        private string phoneNumberField;
        
        private string areaCodeField;
        
        private string driversLicenseField;
        
        private string driversLicenseStateField;
        
        private string driversLicenseExpirationDateField;
        
        private string driversLicenseDateOfIssueField;
        
        private string creditCardNumberField;
        
        private string creditCardExpirationYearField;
        
        private string creditCardExpirationMonthField;
        
        private string creditCardTypeField;
        
        private string requestedByIDField;
        
        private string systemCustomerIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string secondaryNameField;
        
        private string middleNameField;
        
        private string socialSecurityNumberField;
        
        private AddressTypes addressTypeField;
        
        private HousingStatusTypes housingStatusTypeField;
        
        private string streetNumberField;
        
        private string streetNameField;
        
        private string streetDirectionField;
        
        private string streetTypeField;
        
        private string apartmentField;
        
        private string urbanizationNameField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string dOBYearField;
        
        private string dOBDayField;
        
        private string dOBMonthField;
        
        private string salutationField;
        
        private string suffixField;
        
        private string generationCodeField;
        
        private string customerAccessCodeField;
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public PhoneTypes PhoneType {
            get {
                return this.phoneTypeField;
            }
            set {
                this.phoneTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DriversLicense {
            get {
                return this.driversLicenseField;
            }
            set {
                this.driversLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string DriversLicenseState {
            get {
                return this.driversLicenseStateField;
            }
            set {
                this.driversLicenseStateField = value;
            }
        }
        
        /// <remarks/>
        public string DriversLicenseExpirationDate {
            get {
                return this.driversLicenseExpirationDateField;
            }
            set {
                this.driversLicenseExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string DriversLicenseDateOfIssue {
            get {
                return this.driversLicenseDateOfIssueField;
            }
            set {
                this.driversLicenseDateOfIssueField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardExpirationYear {
            get {
                return this.creditCardExpirationYearField;
            }
            set {
                this.creditCardExpirationYearField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardExpirationMonth {
            get {
                return this.creditCardExpirationMonthField;
            }
            set {
                this.creditCardExpirationMonthField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardType {
            get {
                return this.creditCardTypeField;
            }
            set {
                this.creditCardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestedByID {
            get {
                return this.requestedByIDField;
            }
            set {
                this.requestedByIDField = value;
            }
        }
        
        /// <remarks/>
        public string SystemCustomerID {
            get {
                return this.systemCustomerIDField;
            }
            set {
                this.systemCustomerIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string SecondaryName {
            get {
                return this.secondaryNameField;
            }
            set {
                this.secondaryNameField = value;
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNumber {
            get {
                return this.socialSecurityNumberField;
            }
            set {
                this.socialSecurityNumberField = value;
            }
        }
        
        /// <remarks/>
        public AddressTypes AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public HousingStatusTypes HousingStatusType {
            get {
                return this.housingStatusTypeField;
            }
            set {
                this.housingStatusTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetDirection {
            get {
                return this.streetDirectionField;
            }
            set {
                this.streetDirectionField = value;
            }
        }
        
        /// <remarks/>
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }
        
        /// <remarks/>
        public string UrbanizationName {
            get {
                return this.urbanizationNameField;
            }
            set {
                this.urbanizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DOBYear {
            get {
                return this.dOBYearField;
            }
            set {
                this.dOBYearField = value;
            }
        }
        
        /// <remarks/>
        public string DOBDay {
            get {
                return this.dOBDayField;
            }
            set {
                this.dOBDayField = value;
            }
        }
        
        /// <remarks/>
        public string DOBMonth {
            get {
                return this.dOBMonthField;
            }
            set {
                this.dOBMonthField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        public string GenerationCode {
            get {
                return this.generationCodeField;
            }
            set {
                this.generationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerAccessCode {
            get {
                return this.customerAccessCodeField;
            }
            set {
                this.customerAccessCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum PhoneTypes {
        
        /// <remarks/>
        Telephone,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Cellular,
        
        /// <remarks/>
        Pager,
        
        /// <remarks/>
        TollFree,
        
        /// <remarks/>
        MobilePCs,
        
        /// <remarks/>
        NonGeographic,
        
        /// <remarks/>
        SpecialServices,
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        PayPhone,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum AddressTypes {
        
        /// <remarks/>
        ConventionalAddress,
        
        /// <remarks/>
        PostOfficeBox,
        
        /// <remarks/>
        RuralRoute,
        
        /// <remarks/>
        HighwayContract,
        
        /// <remarks/>
        GeneralDelivery,
        
        /// <remarks/>
        FirmAddress,
        
        /// <remarks/>
        Postmaster,
        
        /// <remarks/>
        NotDetermined,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum HousingStatusTypes {
        
        /// <remarks/>
        Own,
        
        /// <remarks/>
        Rent,
        
        /// <remarks/>
        Board,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public partial class ReportResponse {
        
        private string hTMLField;
        
        private string errorMessageField;
        
        private string xMLField;
        
        private int scoreField;
        
        private bool isHitField;
        
        private System.Guid reportGuidField;
        
        private int reportIDField;
        
        private bool isScoredField;
        
        private string hitStatusField;
        
        private ResultValue reportOutcomeField;
        
        private PossibleResults resultField;
        
        private string decisionCodeField;
        
        private string decisionTextField;
        
        private string sSNField;
        
        /// <remarks/>
        public string HTML {
            get {
                return this.hTMLField;
            }
            set {
                this.hTMLField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public int Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHit {
            get {
                return this.isHitField;
            }
            set {
                this.isHitField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ReportGuid {
            get {
                return this.reportGuidField;
            }
            set {
                this.reportGuidField = value;
            }
        }
        
        /// <remarks/>
        public int ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsScored {
            get {
                return this.isScoredField;
            }
            set {
                this.isScoredField = value;
            }
        }
        
        /// <remarks/>
        public string HitStatus {
            get {
                return this.hitStatusField;
            }
            set {
                this.hitStatusField = value;
            }
        }
        
        /// <remarks/>
        public ResultValue ReportOutcome {
            get {
                return this.reportOutcomeField;
            }
            set {
                this.reportOutcomeField = value;
            }
        }
        
        /// <remarks/>
        public PossibleResults Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string DecisionCode {
            get {
                return this.decisionCodeField;
            }
            set {
                this.decisionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DecisionText {
            get {
                return this.decisionTextField;
            }
            set {
                this.decisionTextField = value;
            }
        }
        
        /// <remarks/>
        public string SSN {
            get {
                return this.sSNField;
            }
            set {
                this.sSNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum ResultValue {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        Scored,
        
        /// <remarks/>
        NotScored,
        
        /// <remarks/>
        Declined,
        
        /// <remarks/>
        NoHit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum PossibleResults {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        UNAUTHORIZED,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://blinkws.abarasoftware.com.TU")]
    public enum Services {
        
        /// <remarks/>
        CreditReport,
        
        /// <remarks/>
        IDReport,
        
        /// <remarks/>
        InstantPrescreen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void TestConnectivityCompletedEventHandler(object sender, TestConnectivityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectivityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestConnectivityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetNewReportCompletedEventHandler(object sender, GetNewReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReportResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReportResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetExistingReportCompletedEventHandler(object sender, GetExistingReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExistingReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExistingReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReportResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReportResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591