/** WISE CRM Clean up script for the new database. */
USE [WISE_LOGGING]
GO

BEGIN TRANSACTION

DELETE [dbo].[LG_MessageStackFrames];
DBCC CHECKIDENT ('[dbo].[LG_MessageStackFrames]', RESEED, 1);
DELETE [dbo].[LG_Messages];
DBCC CHECKIDENT('[dbo].[LG_Messages]', RESEED, 1);

ROLLBACK TRANSACTION

/** TRUNCATE LOGS AND DATA. */
ALTER DATABASE [WISE_LOGGING] SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE(WISE_LOGGING_log, 2)
ALTER DATABASE [WISE_LOGGING] SET RECOVERY FULL WITH NO_WAIT
GO