USE [WISE_Receiver]
GO

BEGIN TRANSACTION

DELETE [dbo].[RE_RequestsRaw];
DBCC CHECKIDENT ('[dbo].[RE_RequestsRaw]', RESEED, 0);

DELETE [dbo].[RE_TxtWireRequests];
DBCC CHECKIDENT ('[dbo].[RE_TxtWireRequests]', RESEED, 0);

ROLLBACK TRANSACTION


/** TRUNCATE LOGS AND DATA. */
ALTER DATABASE [WISE_Receiver] SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKFILE(WISE_Receiver_log, 2)
ALTER DATABASE [WISE_Receiver] SET RECOVERY FULL WITH NO_WAIT
GO
