//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace NXS.Logic.MonitoringStations.MoniBounceAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBouncer", Namespace="http://tempuri.org/")]
    public partial class wwwBouncer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback BatchMatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMatchCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMatchResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wwwBouncer() {
            this.Url = global::NXS.Logic.MonitoringStations.Properties.Settings.Default.NXS_Logic_MonitoringStations_MoniBounceAPI_wwwBouncer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MatchCompletedEventHandler MatchCompleted;
        
        /// <remarks/>
        public event BatchMatchCompletedEventHandler BatchMatchCompleted;
        
        /// <remarks/>
        public event SaveMatchCommentCompletedEventHandler SaveMatchCommentCompleted;
        
        /// <remarks/>
        public event GetMatchCommentsCompletedEventHandler GetMatchCommentsCompleted;
        
        /// <remarks/>
        public event SaveMatchResponseCompletedEventHandler SaveMatchResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBouncer/Match", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatchResult Match([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SearchInfo searchInfo) {
            object[] results = this.Invoke("Match", new object[] {
                        searchInfo});
            return ((MatchResult)(results[0]));
        }
        
        /// <remarks/>
        public void MatchAsync(SearchInfo searchInfo) {
            this.MatchAsync(searchInfo, null);
        }
        
        /// <remarks/>
        public void MatchAsync(SearchInfo searchInfo, object userState) {
            if ((this.MatchOperationCompleted == null)) {
                this.MatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatchOperationCompleted);
            }
            this.InvokeAsync("Match", new object[] {
                        searchInfo}, this.MatchOperationCompleted, userState);
        }
        
        private void OnMatchOperationCompleted(object arg) {
            if ((this.MatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatchCompleted(this, new MatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBouncer/BatchMatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
        public MatchResult[] BatchMatch([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")] SearchInfo[] batchInfo) {
            object[] results = this.Invoke("BatchMatch", new object[] {
                        batchInfo});
            return ((MatchResult[])(results[0]));
        }
        
        /// <remarks/>
        public void BatchMatchAsync(SearchInfo[] batchInfo) {
            this.BatchMatchAsync(batchInfo, null);
        }
        
        /// <remarks/>
        public void BatchMatchAsync(SearchInfo[] batchInfo, object userState) {
            if ((this.BatchMatchOperationCompleted == null)) {
                this.BatchMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBatchMatchOperationCompleted);
            }
            this.InvokeAsync("BatchMatch", new object[] {
                        batchInfo}, this.BatchMatchOperationCompleted, userState);
        }
        
        private void OnBatchMatchOperationCompleted(object arg) {
            if ((this.BatchMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BatchMatchCompleted(this, new BatchMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBouncer/SaveMatchComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveMatchComment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MatchComment comment) {
            this.Invoke("SaveMatchComment", new object[] {
                        comment});
        }
        
        /// <remarks/>
        public void SaveMatchCommentAsync(MatchComment comment) {
            this.SaveMatchCommentAsync(comment, null);
        }
        
        /// <remarks/>
        public void SaveMatchCommentAsync(MatchComment comment, object userState) {
            if ((this.SaveMatchCommentOperationCompleted == null)) {
                this.SaveMatchCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMatchCommentOperationCompleted);
            }
            this.InvokeAsync("SaveMatchComment", new object[] {
                        comment}, this.SaveMatchCommentOperationCompleted, userState);
        }
        
        private void OnSaveMatchCommentOperationCompleted(object arg) {
            if ((this.SaveMatchCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMatchCommentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBouncer/GetMatchComments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
        public MatchComment[] GetMatchComments(int MatchID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool MatchIDSpecified) {
            object[] results = this.Invoke("GetMatchComments", new object[] {
                        MatchID,
                        MatchIDSpecified});
            return ((MatchComment[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchCommentsAsync(int MatchID, bool MatchIDSpecified) {
            this.GetMatchCommentsAsync(MatchID, MatchIDSpecified, null);
        }
        
        /// <remarks/>
        public void GetMatchCommentsAsync(int MatchID, bool MatchIDSpecified, object userState) {
            if ((this.GetMatchCommentsOperationCompleted == null)) {
                this.GetMatchCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchCommentsOperationCompleted);
            }
            this.InvokeAsync("GetMatchComments", new object[] {
                        MatchID,
                        MatchIDSpecified}, this.GetMatchCommentsOperationCompleted, userState);
        }
        
        private void OnGetMatchCommentsOperationCompleted(object arg) {
            if ((this.GetMatchCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchCommentsCompleted(this, new GetMatchCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBouncer/SaveMatchResponse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveMatchResponse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MatchResponse matchResponse, out int SaveMatchResponseResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SaveMatchResponseResultSpecified) {
            object[] results = this.Invoke("SaveMatchResponse", new object[] {
                        matchResponse});
            SaveMatchResponseResult = ((int)(results[0]));
            SaveMatchResponseResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SaveMatchResponseAsync(MatchResponse matchResponse) {
            this.SaveMatchResponseAsync(matchResponse, null);
        }
        
        /// <remarks/>
        public void SaveMatchResponseAsync(MatchResponse matchResponse, object userState) {
            if ((this.SaveMatchResponseOperationCompleted == null)) {
                this.SaveMatchResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMatchResponseOperationCompleted);
            }
            this.InvokeAsync("SaveMatchResponse", new object[] {
                        matchResponse}, this.SaveMatchResponseOperationCompleted, userState);
        }
        
        private void OnSaveMatchResponseOperationCompleted(object arg) {
            if ((this.SaveMatchResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMatchResponseCompleted(this, new SaveMatchResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
    public partial class SearchInfo {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string applicationNameField;
        
        private string processNameField;
        
        private string dealerNumberField;
        
        private string dealerNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.Nullable<int> currentSiteIDField;
        
        private bool currentSiteIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProcessName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DealerNumber {
            get {
                return this.dealerNumberField;
            }
            set {
                this.dealerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DealerName {
            get {
                return this.dealerNameField;
            }
            set {
                this.dealerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CurrentSiteID {
            get {
                return this.currentSiteIDField;
            }
            set {
                this.currentSiteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentSiteIDSpecified {
            get {
                return this.currentSiteIDFieldSpecified;
            }
            set {
                this.currentSiteIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
    public partial class MatchResponse {
        
        private int matchIDField;
        
        private bool matchIDFieldSpecified;
        
        private short responseSeqNoField;
        
        private bool responseSeqNoFieldSpecified;
        
        private bool outcomeField;
        
        private bool outcomeFieldSpecified;
        
        /// <remarks/>
        public int MatchID {
            get {
                return this.matchIDField;
            }
            set {
                this.matchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchIDSpecified {
            get {
                return this.matchIDFieldSpecified;
            }
            set {
                this.matchIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short ResponseSeqNo {
            get {
                return this.responseSeqNoField;
            }
            set {
                this.responseSeqNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseSeqNoSpecified {
            get {
                return this.responseSeqNoFieldSpecified;
            }
            set {
                this.responseSeqNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutcomeSpecified {
            get {
                return this.outcomeFieldSpecified;
            }
            set {
                this.outcomeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
    public partial class MatchComment {
        
        private int matchIDField;
        
        private string commentField;
        
        private int responseIDField;
        
        /// <remarks/>
        public int MatchID {
            get {
                return this.matchIDField;
            }
            set {
                this.matchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseID {
            get {
                return this.responseIDField;
            }
            set {
                this.responseIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monitronics.net/bouncer/wcf/2013/08")]
    public partial class MatchResult {
        
        private int matchIDField;
        
        private bool matchIDFieldSpecified;
        
        private int matchCodeField;
        
        private bool matchCodeFieldSpecified;
        
        private int sourceSystemIDField;
        
        private bool sourceSystemIDFieldSpecified;
        
        private int sourceSiteIDField;
        
        private bool sourceSiteIDFieldSpecified;
        
        /// <remarks/>
        public int MatchID {
            get {
                return this.matchIDField;
            }
            set {
                this.matchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchIDSpecified {
            get {
                return this.matchIDFieldSpecified;
            }
            set {
                this.matchIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MatchCode {
            get {
                return this.matchCodeField;
            }
            set {
                this.matchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchCodeSpecified {
            get {
                return this.matchCodeFieldSpecified;
            }
            set {
                this.matchCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SourceSystemID {
            get {
                return this.sourceSystemIDField;
            }
            set {
                this.sourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceSystemIDSpecified {
            get {
                return this.sourceSystemIDFieldSpecified;
            }
            set {
                this.sourceSystemIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SourceSiteID {
            get {
                return this.sourceSiteIDField;
            }
            set {
                this.sourceSiteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceSiteIDSpecified {
            get {
                return this.sourceSiteIDFieldSpecified;
            }
            set {
                this.sourceSiteIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MatchCompletedEventHandler(object sender, MatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void BatchMatchCompletedEventHandler(object sender, BatchMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BatchMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BatchMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatchResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatchResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveMatchCommentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMatchCommentsCompletedEventHandler(object sender, GetMatchCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatchComment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatchComment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveMatchResponseCompletedEventHandler(object sender, SaveMatchResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMatchResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMatchResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int SaveMatchResponseResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SaveMatchResponseResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591