//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSE.FOS.AddressVerification.IS_CorrectAddress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/", ConfigurationName="IS_CorrectAddress.CorrectAddressWebServiceSoap")]
    public interface CorrectAddressWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsGetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsAccountInfo wsGetAccountInfo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsGetAccountAccess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsAccountAccess wsGetAccountAccess(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsCreateBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        bool wsCreateBatch(string username, string password, string batchname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsDeleteBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        bool wsDeleteBatch(string username, string password, string batchname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsGetBatchList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        string[] wsGetBatchList(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsGetPS3553form", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsPS3553 wsGetPS3553form(string username, string password, string batchname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsFindCityState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsCityState[] wsFindCityState(string username, string password, string zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsFindCityCounty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsCityCounty wsFindCityCounty(string username, string password, string zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsFindZipCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsZipCity[] wsFindZipCity(string username, string password, string city, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsCorrectA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsCorrectAddress[] wsCorrectA(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip, string ca_codes, string ca_filler, string batchname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsTigerCA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsCorrectAddress[] wsTigerCA(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip, string ca_codes, string ca_filler, string batchname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.intelligentsearch.com/HostedWebServices/wsStreetSearch2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorrectAddress))]
        SSE.FOS.AddressVerification.IS_CorrectAddress.WsStreetSearch[] wsStreetSearch2(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsAccountInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int searchesLeftField;
        
        private int returnCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SearchesLeft {
            get {
                return this.searchesLeftField;
            }
            set {
                this.searchesLeftField = value;
                this.RaisePropertyChanged("SearchesLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("ReturnCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsStreetSearch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string streetNumberField;
        
        private string preDirectionalField;
        
        private string streetNameField;
        
        private string streetSuffixField;
        
        private string postDirectionalField;
        
        private string secondaryDesignationField;
        
        private string secondaryNumberField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipAddonField;
        
        private string zipField;
        
        private string addonField;
        
        private string recordTypeField;
        
        private string carrierRouteField;
        
        private string firmRecipientField;
        
        private string urbanizationField;
        
        private string financeNumberField;
        
        private string errorDescField;
        
        private int searchesLeftField;
        
        private string scoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PreDirectional {
            get {
                return this.preDirectionalField;
            }
            set {
                this.preDirectionalField = value;
                this.RaisePropertyChanged("PreDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
                this.RaisePropertyChanged("StreetSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostDirectional {
            get {
                return this.postDirectionalField;
            }
            set {
                this.postDirectionalField = value;
                this.RaisePropertyChanged("PostDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SecondaryDesignation {
            get {
                return this.secondaryDesignationField;
            }
            set {
                this.secondaryDesignationField = value;
                this.RaisePropertyChanged("SecondaryDesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SecondaryNumber {
            get {
                return this.secondaryNumberField;
            }
            set {
                this.secondaryNumberField = value;
                this.RaisePropertyChanged("SecondaryNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZipAddon {
            get {
                return this.zipAddonField;
            }
            set {
                this.zipAddonField = value;
                this.RaisePropertyChanged("ZipAddon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Addon {
            get {
                return this.addonField;
            }
            set {
                this.addonField = value;
                this.RaisePropertyChanged("Addon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FirmRecipient {
            get {
                return this.firmRecipientField;
            }
            set {
                this.firmRecipientField = value;
                this.RaisePropertyChanged("FirmRecipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Urbanization {
            get {
                return this.urbanizationField;
            }
            set {
                this.urbanizationField = value;
                this.RaisePropertyChanged("Urbanization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FinanceNumber {
            get {
                return this.financeNumberField;
            }
            set {
                this.financeNumberField = value;
                this.RaisePropertyChanged("FinanceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("ErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int SearchesLeft {
            get {
                return this.searchesLeftField;
            }
            set {
                this.searchesLeftField = value;
                this.RaisePropertyChanged("SearchesLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WsCorrectAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class CorrectAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string streetNumberField;
        
        private string preDirectionalField;
        
        private string streetNameField;
        
        private string streetSuffixField;
        
        private string postDirectionalField;
        
        private string secondaryDesignationField;
        
        private string secondaryNumberField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipAddonField;
        
        private string zipField;
        
        private string addonField;
        
        private string lOTNumberField;
        
        private string dPCCheckdigitField;
        
        private string recordTypeField;
        
        private string deliveryLine1Field;
        
        private string deliveryLine2Field;
        
        private string lastLineField;
        
        private string lACSField;
        
        private string carrierRouteField;
        
        private string pMBDesignatorField;
        
        private string firmRecipientField;
        
        private string urbanizationField;
        
        private string countyNameField;
        
        private string countyNumberField;
        
        private string fillerField;
        
        private string geoTLIDField;
        
        private string geoMatchFlagField;
        
        private string geoTractField;
        
        private string geoBlockField;
        
        private string geofLatField;
        
        private string geotLatField;
        
        private string geofLongField;
        
        private string geotLongField;
        
        private string geoAddonEndField;
        
        private string geoAddonStartField;
        
        private string geoRetCodeField;
        
        private string geoErrCodesField;
        
        private string returnCodesField;
        
        private string errorCodesField;
        
        private string errorDescField;
        
        private int searchesLeftField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PreDirectional {
            get {
                return this.preDirectionalField;
            }
            set {
                this.preDirectionalField = value;
                this.RaisePropertyChanged("PreDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
                this.RaisePropertyChanged("StreetSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PostDirectional {
            get {
                return this.postDirectionalField;
            }
            set {
                this.postDirectionalField = value;
                this.RaisePropertyChanged("PostDirectional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SecondaryDesignation {
            get {
                return this.secondaryDesignationField;
            }
            set {
                this.secondaryDesignationField = value;
                this.RaisePropertyChanged("SecondaryDesignation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SecondaryNumber {
            get {
                return this.secondaryNumberField;
            }
            set {
                this.secondaryNumberField = value;
                this.RaisePropertyChanged("SecondaryNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ZipAddon {
            get {
                return this.zipAddonField;
            }
            set {
                this.zipAddonField = value;
                this.RaisePropertyChanged("ZipAddon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Addon {
            get {
                return this.addonField;
            }
            set {
                this.addonField = value;
                this.RaisePropertyChanged("Addon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LOTNumber {
            get {
                return this.lOTNumberField;
            }
            set {
                this.lOTNumberField = value;
                this.RaisePropertyChanged("LOTNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DPCCheckdigit {
            get {
                return this.dPCCheckdigitField;
            }
            set {
                this.dPCCheckdigitField = value;
                this.RaisePropertyChanged("DPCCheckdigit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
                this.RaisePropertyChanged("RecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DeliveryLine1 {
            get {
                return this.deliveryLine1Field;
            }
            set {
                this.deliveryLine1Field = value;
                this.RaisePropertyChanged("DeliveryLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DeliveryLine2 {
            get {
                return this.deliveryLine2Field;
            }
            set {
                this.deliveryLine2Field = value;
                this.RaisePropertyChanged("DeliveryLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string LastLine {
            get {
                return this.lastLineField;
            }
            set {
                this.lastLineField = value;
                this.RaisePropertyChanged("LastLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LACS {
            get {
                return this.lACSField;
            }
            set {
                this.lACSField = value;
                this.RaisePropertyChanged("LACS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CarrierRoute {
            get {
                return this.carrierRouteField;
            }
            set {
                this.carrierRouteField = value;
                this.RaisePropertyChanged("CarrierRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PMBDesignator {
            get {
                return this.pMBDesignatorField;
            }
            set {
                this.pMBDesignatorField = value;
                this.RaisePropertyChanged("PMBDesignator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string FirmRecipient {
            get {
                return this.firmRecipientField;
            }
            set {
                this.firmRecipientField = value;
                this.RaisePropertyChanged("FirmRecipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Urbanization {
            get {
                return this.urbanizationField;
            }
            set {
                this.urbanizationField = value;
                this.RaisePropertyChanged("Urbanization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CountyNumber {
            get {
                return this.countyNumberField;
            }
            set {
                this.countyNumberField = value;
                this.RaisePropertyChanged("CountyNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Filler {
            get {
                return this.fillerField;
            }
            set {
                this.fillerField = value;
                this.RaisePropertyChanged("Filler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string GeoTLID {
            get {
                return this.geoTLIDField;
            }
            set {
                this.geoTLIDField = value;
                this.RaisePropertyChanged("GeoTLID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string GeoMatchFlag {
            get {
                return this.geoMatchFlagField;
            }
            set {
                this.geoMatchFlagField = value;
                this.RaisePropertyChanged("GeoMatchFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string GeoTract {
            get {
                return this.geoTractField;
            }
            set {
                this.geoTractField = value;
                this.RaisePropertyChanged("GeoTract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string GeoBlock {
            get {
                return this.geoBlockField;
            }
            set {
                this.geoBlockField = value;
                this.RaisePropertyChanged("GeoBlock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string GeofLat {
            get {
                return this.geofLatField;
            }
            set {
                this.geofLatField = value;
                this.RaisePropertyChanged("GeofLat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string GeotLat {
            get {
                return this.geotLatField;
            }
            set {
                this.geotLatField = value;
                this.RaisePropertyChanged("GeotLat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string GeofLong {
            get {
                return this.geofLongField;
            }
            set {
                this.geofLongField = value;
                this.RaisePropertyChanged("GeofLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string GeotLong {
            get {
                return this.geotLongField;
            }
            set {
                this.geotLongField = value;
                this.RaisePropertyChanged("GeotLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string GeoAddonEnd {
            get {
                return this.geoAddonEndField;
            }
            set {
                this.geoAddonEndField = value;
                this.RaisePropertyChanged("GeoAddonEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string GeoAddonStart {
            get {
                return this.geoAddonStartField;
            }
            set {
                this.geoAddonStartField = value;
                this.RaisePropertyChanged("GeoAddonStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string GeoRetCode {
            get {
                return this.geoRetCodeField;
            }
            set {
                this.geoRetCodeField = value;
                this.RaisePropertyChanged("GeoRetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string GeoErrCodes {
            get {
                return this.geoErrCodesField;
            }
            set {
                this.geoErrCodesField = value;
                this.RaisePropertyChanged("GeoErrCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string ReturnCodes {
            get {
                return this.returnCodesField;
            }
            set {
                this.returnCodesField = value;
                this.RaisePropertyChanged("ReturnCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ErrorCodes {
            get {
                return this.errorCodesField;
            }
            set {
                this.errorCodesField = value;
                this.RaisePropertyChanged("ErrorCodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("ErrorDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public int SearchesLeft {
            get {
                return this.searchesLeftField;
            }
            set {
                this.searchesLeftField = value;
                this.RaisePropertyChanged("SearchesLeft");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsCorrectAddress : CorrectAddress {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsZipCity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private int searchLeftField;
        
        private string errorDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SearchLeft {
            get {
                return this.searchLeftField;
            }
            set {
                this.searchLeftField = value;
                this.RaisePropertyChanged("SearchLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("ErrorDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsCityCounty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipField;
        
        private string cityField;
        
        private string stateField;
        
        private string countyNameField;
        
        private string countyNumField;
        
        private int searchLeftField;
        
        private string errorDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountyNum {
            get {
                return this.countyNumField;
            }
            set {
                this.countyNumField = value;
                this.RaisePropertyChanged("CountyNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SearchLeft {
            get {
                return this.searchLeftField;
            }
            set {
                this.searchLeftField = value;
                this.RaisePropertyChanged("SearchLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("ErrorDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsCityState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zipField;
        
        private string cityField;
        
        private string stateField;
        
        private string countyNameField;
        
        private int searchLeftField;
        
        private string errorDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CountyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("CountyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SearchLeft {
            get {
                return this.searchLeftField;
            }
            set {
                this.searchLeftField = value;
                this.RaisePropertyChanged("SearchLeft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
                this.RaisePropertyChanged("ErrorDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsPS3553 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cAdateField;
        
        private string companyField;
        
        private string softwareField;
        
        private string configurationField;
        
        private int recordCountField;
        
        private int zipCountField;
        
        private int addonCountField;
        
        private int cRouteCountField;
        
        private int lOTCountField;
        
        private int dPCCountField;
        
        private int lACSCountField;
        
        private int eWSCountField;
        
        private int dPVCountField;
        
        private int hDefaultCountField;
        
        private int hExactCountField;
        
        private int rRDefaultCountField;
        
        private int rRExactCountField;
        
        private int rDICountField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CAdate {
            get {
                return this.cAdateField;
            }
            set {
                this.cAdateField = value;
                this.RaisePropertyChanged("CAdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
                this.RaisePropertyChanged("Software");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("RecordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ZipCount {
            get {
                return this.zipCountField;
            }
            set {
                this.zipCountField = value;
                this.RaisePropertyChanged("ZipCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int AddonCount {
            get {
                return this.addonCountField;
            }
            set {
                this.addonCountField = value;
                this.RaisePropertyChanged("AddonCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CRouteCount {
            get {
                return this.cRouteCountField;
            }
            set {
                this.cRouteCountField = value;
                this.RaisePropertyChanged("CRouteCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int LOTCount {
            get {
                return this.lOTCountField;
            }
            set {
                this.lOTCountField = value;
                this.RaisePropertyChanged("LOTCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DPCCount {
            get {
                return this.dPCCountField;
            }
            set {
                this.dPCCountField = value;
                this.RaisePropertyChanged("DPCCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LACSCount {
            get {
                return this.lACSCountField;
            }
            set {
                this.lACSCountField = value;
                this.RaisePropertyChanged("LACSCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int EWSCount {
            get {
                return this.eWSCountField;
            }
            set {
                this.eWSCountField = value;
                this.RaisePropertyChanged("EWSCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int DPVCount {
            get {
                return this.dPVCountField;
            }
            set {
                this.dPVCountField = value;
                this.RaisePropertyChanged("DPVCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int HDefaultCount {
            get {
                return this.hDefaultCountField;
            }
            set {
                this.hDefaultCountField = value;
                this.RaisePropertyChanged("HDefaultCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int HExactCount {
            get {
                return this.hExactCountField;
            }
            set {
                this.hExactCountField = value;
                this.RaisePropertyChanged("HExactCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int RRDefaultCount {
            get {
                return this.rRDefaultCountField;
            }
            set {
                this.rRDefaultCountField = value;
                this.RaisePropertyChanged("RRDefaultCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int RRExactCount {
            get {
                return this.rRExactCountField;
            }
            set {
                this.rRExactCountField = value;
                this.RaisePropertyChanged("RRExactCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int RDICount {
            get {
                return this.rDICountField;
            }
            set {
                this.rDICountField = value;
                this.RaisePropertyChanged("RDICount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intelligentsearch.com/HostedWebServices/")]
    public partial class WsAccountAccess : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool caField;
        
        private bool geoField;
        
        private bool dpvField;
        
        private bool lACSLinkField;
        
        private bool officeAddinField;
        
        private bool webClientField;
        
        private string currentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Ca {
            get {
                return this.caField;
            }
            set {
                this.caField = value;
                this.RaisePropertyChanged("Ca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Geo {
            get {
                return this.geoField;
            }
            set {
                this.geoField = value;
                this.RaisePropertyChanged("Geo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Dpv {
            get {
                return this.dpvField;
            }
            set {
                this.dpvField = value;
                this.RaisePropertyChanged("Dpv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool LACSLink {
            get {
                return this.lACSLinkField;
            }
            set {
                this.lACSLinkField = value;
                this.RaisePropertyChanged("LACSLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool OfficeAddin {
            get {
                return this.officeAddinField;
            }
            set {
                this.officeAddinField = value;
                this.RaisePropertyChanged("OfficeAddin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool WebClient {
            get {
                return this.webClientField;
            }
            set {
                this.webClientField = value;
                this.RaisePropertyChanged("WebClient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CurrentDate {
            get {
                return this.currentDateField;
            }
            set {
                this.currentDateField = value;
                this.RaisePropertyChanged("CurrentDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorrectAddressWebServiceSoapChannel : SSE.FOS.AddressVerification.IS_CorrectAddress.CorrectAddressWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorrectAddressWebServiceSoapClient : System.ServiceModel.ClientBase<SSE.FOS.AddressVerification.IS_CorrectAddress.CorrectAddressWebServiceSoap>, SSE.FOS.AddressVerification.IS_CorrectAddress.CorrectAddressWebServiceSoap {
        
        public CorrectAddressWebServiceSoapClient() {
        }
        
        public CorrectAddressWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorrectAddressWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrectAddressWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrectAddressWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsAccountInfo wsGetAccountInfo(string username, string password) {
            return base.Channel.wsGetAccountInfo(username, password);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsAccountAccess wsGetAccountAccess(string username, string password) {
            return base.Channel.wsGetAccountAccess(username, password);
        }
        
        public bool wsCreateBatch(string username, string password, string batchname) {
            return base.Channel.wsCreateBatch(username, password, batchname);
        }
        
        public bool wsDeleteBatch(string username, string password, string batchname) {
            return base.Channel.wsDeleteBatch(username, password, batchname);
        }
        
        public string[] wsGetBatchList(string username, string password) {
            return base.Channel.wsGetBatchList(username, password);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsPS3553 wsGetPS3553form(string username, string password, string batchname) {
            return base.Channel.wsGetPS3553form(username, password, batchname);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsCityState[] wsFindCityState(string username, string password, string zip) {
            return base.Channel.wsFindCityState(username, password, zip);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsCityCounty wsFindCityCounty(string username, string password, string zip) {
            return base.Channel.wsFindCityCounty(username, password, zip);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsZipCity[] wsFindZipCity(string username, string password, string city, string state) {
            return base.Channel.wsFindZipCity(username, password, city, state);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsCorrectAddress[] wsCorrectA(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip, string ca_codes, string ca_filler, string batchname) {
            return base.Channel.wsCorrectA(username, password, firmname, urbanization, delivery_line_1, delivery_line_2, city_state_zip, ca_codes, ca_filler, batchname);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsCorrectAddress[] wsTigerCA(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip, string ca_codes, string ca_filler, string batchname) {
            return base.Channel.wsTigerCA(username, password, firmname, urbanization, delivery_line_1, delivery_line_2, city_state_zip, ca_codes, ca_filler, batchname);
        }
        
        public SSE.FOS.AddressVerification.IS_CorrectAddress.WsStreetSearch[] wsStreetSearch2(string username, string password, string firmname, string urbanization, string delivery_line_1, string delivery_line_2, string city_state_zip) {
            return base.Channel.wsStreetSearch2(username, password, firmname, urbanization, delivery_line_1, delivery_line_2, city_state_zip);
        }
    }
}
