//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace NXS.Logic.MonitoringStations.MoniWSI45 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSISoap", Namespace="https://mimasweb.monitronics.net/MIDI/")]
    public partial class WSI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ApplicationIDHeader applicationIDHeaderValueField;
        
        private System.Threading.SendOrPostCallback AccountOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImmediateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback PartialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCreditRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePurchaseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDealerCMRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimezoneFromZipcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebServiceVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSI() {
            this.Url = global::NXS.Logic.MonitoringStations.Properties.Settings.Default.NXS_Logic_MonitoringStations_MoniWSI45_WSI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ApplicationIDHeader ApplicationIDHeaderValue {
            get {
                return this.applicationIDHeaderValueField;
            }
            set {
                this.applicationIDHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccountOnlineCompletedEventHandler AccountOnlineCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event ImmediateCompletedEventHandler ImmediateCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event PartialCompletedEventHandler PartialCompleted;
        
        /// <remarks/>
        public event GetCreditRequestCompletedEventHandler GetCreditRequestCompleted;
        
        /// <remarks/>
        public event UpdateCreditRequestCompletedEventHandler UpdateCreditRequestCompleted;
        
        /// <remarks/>
        public event GetPurchaseInfoCompletedEventHandler GetPurchaseInfoCompleted;
        
        /// <remarks/>
        public event UpdatePurchaseInfoCompletedEventHandler UpdatePurchaseInfoCompleted;
        
        /// <remarks/>
        public event GetDealerCMRatesCompletedEventHandler GetDealerCMRatesCompleted;
        
        /// <remarks/>
        public event GetTimezoneFromZipcodeCompletedEventHandler GetTimezoneFromZipcodeCompleted;
        
        /// <remarks/>
        public event GetWebServiceVersionCompletedEventHandler GetWebServiceVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationIDHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/AccountOnline", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AccountOnline(string userName, string password, string csNo, string xml, string creditRequestXml, string purchaseInfoXml) {
            object[] results = this.Invoke("AccountOnline", new object[] {
                        userName,
                        password,
                        csNo,
                        xml,
                        creditRequestXml,
                        purchaseInfoXml});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AccountOnlineAsync(string userName, string password, string csNo, string xml, string creditRequestXml, string purchaseInfoXml) {
            this.AccountOnlineAsync(userName, password, csNo, xml, creditRequestXml, purchaseInfoXml, null);
        }
        
        /// <remarks/>
        public void AccountOnlineAsync(string userName, string password, string csNo, string xml, string creditRequestXml, string purchaseInfoXml, object userState) {
            if ((this.AccountOnlineOperationCompleted == null)) {
                this.AccountOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountOnlineOperationCompleted);
            }
            this.InvokeAsync("AccountOnline", new object[] {
                        userName,
                        password,
                        csNo,
                        xml,
                        creditRequestXml,
                        purchaseInfoXml}, this.AccountOnlineOperationCompleted, userState);
        }
        
        private void OnAccountOnlineOperationCompleted(object arg) {
            if ((this.AccountOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountOnlineCompleted(this, new AccountOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetData", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetData(string Entity, string UserID, string Password, string CustomerNumber, string XMLData) {
            object[] results = this.Invoke("GetData", new object[] {
                        Entity,
                        UserID,
                        Password,
                        CustomerNumber,
                        XMLData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string Entity, string UserID, string Password, string CustomerNumber, string XMLData) {
            this.GetDataAsync(Entity, UserID, Password, CustomerNumber, XMLData, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string Entity, string UserID, string Password, string CustomerNumber, string XMLData, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        Entity,
                        UserID,
                        Password,
                        CustomerNumber,
                        XMLData}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationIDHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/Immediate", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Immediate(string Entity, string UserID, string Password, string CustomerNumber, string XMLData) {
            object[] results = this.Invoke("Immediate", new object[] {
                        Entity,
                        UserID,
                        Password,
                        CustomerNumber,
                        XMLData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ImmediateAsync(string Entity, string UserID, string Password, string CustomerNumber, string XMLData) {
            this.ImmediateAsync(Entity, UserID, Password, CustomerNumber, XMLData, null);
        }
        
        /// <remarks/>
        public void ImmediateAsync(string Entity, string UserID, string Password, string CustomerNumber, string XMLData, object userState) {
            if ((this.ImmediateOperationCompleted == null)) {
                this.ImmediateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImmediateOperationCompleted);
            }
            this.InvokeAsync("Immediate", new object[] {
                        Entity,
                        UserID,
                        Password,
                        CustomerNumber,
                        XMLData}, this.ImmediateOperationCompleted, userState);
        }
        
        private void OnImmediateOperationCompleted(object arg) {
            if ((this.ImmediateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImmediateCompleted(this, new ImmediateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationIDHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/Update", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Update(string userName, string password, string reqType, string csNo, string xml) {
            object[] results = this.Invoke("Update", new object[] {
                        userName,
                        password,
                        reqType,
                        csNo,
                        xml});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(string userName, string password, string reqType, string csNo, string xml) {
            this.UpdateAsync(userName, password, reqType, csNo, xml, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string userName, string password, string reqType, string csNo, string xml, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        userName,
                        password,
                        reqType,
                        csNo,
                        xml}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApplicationIDHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/Partial", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Partial(string userName, string password, string reqType, string csNo, int wsiBatchNo) {
            object[] results = this.Invoke("Partial", new object[] {
                        userName,
                        password,
                        reqType,
                        csNo,
                        wsiBatchNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PartialAsync(string userName, string password, string reqType, string csNo, int wsiBatchNo) {
            this.PartialAsync(userName, password, reqType, csNo, wsiBatchNo, null);
        }
        
        /// <remarks/>
        public void PartialAsync(string userName, string password, string reqType, string csNo, int wsiBatchNo, object userState) {
            if ((this.PartialOperationCompleted == null)) {
                this.PartialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPartialOperationCompleted);
            }
            this.InvokeAsync("Partial", new object[] {
                        userName,
                        password,
                        reqType,
                        csNo,
                        wsiBatchNo}, this.PartialOperationCompleted, userState);
        }
        
        private void OnPartialOperationCompleted(object arg) {
            if ((this.PartialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PartialCompleted(this, new PartialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetCreditRequest", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCreditRequest(string userName, string password, string cs) {
            object[] results = this.Invoke("GetCreditRequest", new object[] {
                        userName,
                        password,
                        cs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditRequestAsync(string userName, string password, string cs) {
            this.GetCreditRequestAsync(userName, password, cs, null);
        }
        
        /// <remarks/>
        public void GetCreditRequestAsync(string userName, string password, string cs, object userState) {
            if ((this.GetCreditRequestOperationCompleted == null)) {
                this.GetCreditRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditRequestOperationCompleted);
            }
            this.InvokeAsync("GetCreditRequest", new object[] {
                        userName,
                        password,
                        cs}, this.GetCreditRequestOperationCompleted, userState);
        }
        
        private void OnGetCreditRequestOperationCompleted(object arg) {
            if ((this.GetCreditRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditRequestCompleted(this, new GetCreditRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/UpdateCreditRequest", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCreditRequest(string userName, string password, string xml) {
            this.Invoke("UpdateCreditRequest", new object[] {
                        userName,
                        password,
                        xml});
        }
        
        /// <remarks/>
        public void UpdateCreditRequestAsync(string userName, string password, string xml) {
            this.UpdateCreditRequestAsync(userName, password, xml, null);
        }
        
        /// <remarks/>
        public void UpdateCreditRequestAsync(string userName, string password, string xml, object userState) {
            if ((this.UpdateCreditRequestOperationCompleted == null)) {
                this.UpdateCreditRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCreditRequestOperationCompleted);
            }
            this.InvokeAsync("UpdateCreditRequest", new object[] {
                        userName,
                        password,
                        xml}, this.UpdateCreditRequestOperationCompleted, userState);
        }
        
        private void OnUpdateCreditRequestOperationCompleted(object arg) {
            if ((this.UpdateCreditRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCreditRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetPurchaseInfo", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPurchaseInfo(string userName, string password, string cs) {
            object[] results = this.Invoke("GetPurchaseInfo", new object[] {
                        userName,
                        password,
                        cs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseInfoAsync(string userName, string password, string cs) {
            this.GetPurchaseInfoAsync(userName, password, cs, null);
        }
        
        /// <remarks/>
        public void GetPurchaseInfoAsync(string userName, string password, string cs, object userState) {
            if ((this.GetPurchaseInfoOperationCompleted == null)) {
                this.GetPurchaseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseInfoOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseInfo", new object[] {
                        userName,
                        password,
                        cs}, this.GetPurchaseInfoOperationCompleted, userState);
        }
        
        private void OnGetPurchaseInfoOperationCompleted(object arg) {
            if ((this.GetPurchaseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseInfoCompleted(this, new GetPurchaseInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/UpdatePurchaseInfo", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePurchaseInfo(string userName, string password, string xml) {
            this.Invoke("UpdatePurchaseInfo", new object[] {
                        userName,
                        password,
                        xml});
        }
        
        /// <remarks/>
        public void UpdatePurchaseInfoAsync(string userName, string password, string xml) {
            this.UpdatePurchaseInfoAsync(userName, password, xml, null);
        }
        
        /// <remarks/>
        public void UpdatePurchaseInfoAsync(string userName, string password, string xml, object userState) {
            if ((this.UpdatePurchaseInfoOperationCompleted == null)) {
                this.UpdatePurchaseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePurchaseInfoOperationCompleted);
            }
            this.InvokeAsync("UpdatePurchaseInfo", new object[] {
                        userName,
                        password,
                        xml}, this.UpdatePurchaseInfoOperationCompleted, userState);
        }
        
        private void OnUpdatePurchaseInfoOperationCompleted(object arg) {
            if ((this.UpdatePurchaseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePurchaseInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetDealerCMRates", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetDealerCMRates(int dealerNumber, int countryNumber) {
            object[] results = this.Invoke("GetDealerCMRates", new object[] {
                        dealerNumber,
                        countryNumber});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetDealerCMRatesAsync(int dealerNumber, int countryNumber) {
            this.GetDealerCMRatesAsync(dealerNumber, countryNumber, null);
        }
        
        /// <remarks/>
        public void GetDealerCMRatesAsync(int dealerNumber, int countryNumber, object userState) {
            if ((this.GetDealerCMRatesOperationCompleted == null)) {
                this.GetDealerCMRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDealerCMRatesOperationCompleted);
            }
            this.InvokeAsync("GetDealerCMRates", new object[] {
                        dealerNumber,
                        countryNumber}, this.GetDealerCMRatesOperationCompleted, userState);
        }
        
        private void OnGetDealerCMRatesOperationCompleted(object arg) {
            if ((this.GetDealerCMRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDealerCMRatesCompleted(this, new GetDealerCMRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetTimezoneFromZipcode", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetTimezoneFromZipcode(string zipcode) {
            object[] results = this.Invoke("GetTimezoneFromZipcode", new object[] {
                        zipcode});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimezoneFromZipcodeAsync(string zipcode) {
            this.GetTimezoneFromZipcodeAsync(zipcode, null);
        }
        
        /// <remarks/>
        public void GetTimezoneFromZipcodeAsync(string zipcode, object userState) {
            if ((this.GetTimezoneFromZipcodeOperationCompleted == null)) {
                this.GetTimezoneFromZipcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimezoneFromZipcodeOperationCompleted);
            }
            this.InvokeAsync("GetTimezoneFromZipcode", new object[] {
                        zipcode}, this.GetTimezoneFromZipcodeOperationCompleted, userState);
        }
        
        private void OnGetTimezoneFromZipcodeOperationCompleted(object arg) {
            if ((this.GetTimezoneFromZipcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimezoneFromZipcodeCompleted(this, new GetTimezoneFromZipcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://mimasweb.monitronics.net/MIDI/GetWebServiceVersion", RequestNamespace="https://mimasweb.monitronics.net/MIDI/", ResponseNamespace="https://mimasweb.monitronics.net/MIDI/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWebServiceVersion() {
            object[] results = this.Invoke("GetWebServiceVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebServiceVersionAsync() {
            this.GetWebServiceVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetWebServiceVersionAsync(object userState) {
            if ((this.GetWebServiceVersionOperationCompleted == null)) {
                this.GetWebServiceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebServiceVersionOperationCompleted);
            }
            this.InvokeAsync("GetWebServiceVersion", new object[0], this.GetWebServiceVersionOperationCompleted, userState);
        }
        
        private void OnGetWebServiceVersionOperationCompleted(object arg) {
            if ((this.GetWebServiceVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebServiceVersionCompleted(this, new GetWebServiceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://mimasweb.monitronics.net/MIDI/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://mimasweb.monitronics.net/MIDI/", IsNullable=false)]
    public partial class ApplicationIDHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string appIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string appID {
            get {
                return this.appIDField;
            }
            set {
                this.appIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AccountOnlineCompletedEventHandler(object sender, AccountOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ImmediateCompletedEventHandler(object sender, ImmediateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImmediateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImmediateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void PartialCompletedEventHandler(object sender, PartialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PartialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PartialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetCreditRequestCompletedEventHandler(object sender, GetCreditRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateCreditRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPurchaseInfoCompletedEventHandler(object sender, GetPurchaseInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdatePurchaseInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDealerCMRatesCompletedEventHandler(object sender, GetDealerCMRatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDealerCMRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDealerCMRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetTimezoneFromZipcodeCompletedEventHandler(object sender, GetTimezoneFromZipcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimezoneFromZipcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimezoneFromZipcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetWebServiceVersionCompletedEventHandler(object sender, GetWebServiceVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebServiceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebServiceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591