//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOS.FOS.CellStation.AlarmComWebServiceValidate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.alarm.com/WebServices", ConfigurationName="AlarmComWebServiceValidate.ValidateSoap")]
    public interface ValidateSoap {
        
        // CODEGEN: Generating message contract since message ValidateSerialNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/ValidateSerialNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse ValidateSerialNumber(SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/ValidateSerialNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse> ValidateSerialNumberAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest request);
        
        // CODEGEN: Generating message contract since message CheckCoverageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/CheckCoverage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse CheckCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/CheckCoverage", ReplyAction="*")]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse> CheckCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest request);
        
        // CODEGEN: Generating message contract since message CheckModemAndCoverageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/CheckModemAndCoverage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse CheckModemAndCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.alarm.com/WebServices/CheckModemAndCoverage", ReplyAction="*")]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse> CheckModemAndCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class CombinedValidationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SerialNumberValidationResult serialNumberResultField;
        
        private CoverageResultEnum coverageResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SerialNumberValidationResult SerialNumberResult {
            get {
                return this.serialNumberResultField;
            }
            set {
                this.serialNumberResultField = value;
                this.RaisePropertyChanged("SerialNumberResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CoverageResultEnum CoverageResult {
            get {
                return this.coverageResultField;
            }
            set {
                this.coverageResultField = value;
                this.RaisePropertyChanged("CoverageResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class SerialNumberValidationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool validField;
        
        private string errorDescriptionField;
        
        private bool isReferralField;
        
        private int referralServicePlanIdField;
        
        private int referralPackageIdField;
        
        private ModemInfo modemInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("Valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsReferral {
            get {
                return this.isReferralField;
            }
            set {
                this.isReferralField = value;
                this.RaisePropertyChanged("IsReferral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ReferralServicePlanId {
            get {
                return this.referralServicePlanIdField;
            }
            set {
                this.referralServicePlanIdField = value;
                this.RaisePropertyChanged("ReferralServicePlanId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ReferralPackageId {
            get {
                return this.referralPackageIdField;
            }
            set {
                this.referralPackageIdField = value;
                this.RaisePropertyChanged("ReferralPackageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ModemInfo ModemInfo {
            get {
                return this.modemInfoField;
            }
            set {
                this.modemInfoField = value;
                this.RaisePropertyChanged("ModemInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class ModemInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string modemSerialField;
        
        private int firmwareVersionField;
        
        private NetworkEnum networkField;
        
        private bool twoWayVoiceCapableField;
        
        private RadioNetworkTypeEnum radioNetworkTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ModemSerial {
            get {
                return this.modemSerialField;
            }
            set {
                this.modemSerialField = value;
                this.RaisePropertyChanged("ModemSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FirmwareVersion {
            get {
                return this.firmwareVersionField;
            }
            set {
                this.firmwareVersionField = value;
                this.RaisePropertyChanged("FirmwareVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NetworkEnum Network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
                this.RaisePropertyChanged("Network");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool TwoWayVoiceCapable {
            get {
                return this.twoWayVoiceCapableField;
            }
            set {
                this.twoWayVoiceCapableField = value;
                this.RaisePropertyChanged("TwoWayVoiceCapable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RadioNetworkTypeEnum RadioNetworkType {
            get {
                return this.radioNetworkTypeField;
            }
            set {
                this.radioNetworkTypeField = value;
                this.RaisePropertyChanged("RadioNetworkType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public enum NetworkEnum {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        Skytel,
        
        /// <remarks/>
        WebLink,
        
        /// <remarks/>
        GSM,
        
        /// <remarks/>
        Broadband,
        
        /// <remarks/>
        GSM2,
        
        /// <remarks/>
        GsmCanada,
        
        /// <remarks/>
        TMobile,
        
        /// <remarks/>
        TMobilePartner1,
        
        /// <remarks/>
        GsmCanada2,
        
        /// <remarks/>
        Rogers,
        
        /// <remarks/>
        RogersPartner1,
        
        /// <remarks/>
        ATTPartner1,
        
        /// <remarks/>
        Verizon,
        
        /// <remarks/>
        Telefonica,
        
        /// <remarks/>
        DealerProvisioned,
        
        /// <remarks/>
        Oi,
        
        /// <remarks/>
        Vivo,
        
        /// <remarks/>
        Vodafone,
        
        /// <remarks/>
        VerizonPartner1,
        
        /// <remarks/>
        Turkcell,
        
        /// <remarks/>
        USCellular,
        
        /// <remarks/>
        Digicel,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public enum RadioNetworkTypeEnum {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Broadband,
        
        /// <remarks/>
        GPRS,
        
        /// <remarks/>
        CDMA,
        
        /// <remarks/>
        HSPA_GPRS,
        
        /// <remarks/>
        TwoWayPager,
        
        /// <remarks/>
        LTE_VZW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public enum CoverageResultEnum {
        
        /// <remarks/>
        NotChecked,
        
        /// <remarks/>
        FullCoverage,
        
        /// <remarks/>
        MostlyCovered,
        
        /// <remarks/>
        NoCoverage,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        BadZip,
        
        /// <remarks/>
        PartialCoverage,
        
        /// <remarks/>
        NotSupported,
        
        /// <remarks/>
        NotOffered,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressWithName))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressWithCoordinates))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string street1Field;
        
        private string street2Field;
        
        private string subCityField;
        
        private string cityField;
        
        private string subStateField;
        
        private string stateField;
        
        private string zipField;
        
        private CountryEnum countryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("Street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("Street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SubCity {
            get {
                return this.subCityField;
            }
            set {
                this.subCityField = value;
                this.RaisePropertyChanged("SubCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubState {
            get {
                return this.subStateField;
            }
            set {
                this.subStateField = value;
                this.RaisePropertyChanged("SubState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public CountryEnum CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("CountryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public enum CountryEnum {
        
        /// <remarks/>
        NotSet,
        
        /// <remarks/>
        USA,
        
        /// <remarks/>
        Canada,
        
        /// <remarks/>
        Brazil,
        
        /// <remarks/>
        Mexico,
        
        /// <remarks/>
        SouthAfrica,
        
        /// <remarks/>
        Chile,
        
        /// <remarks/>
        Argentina,
        
        /// <remarks/>
        Colombia,
        
        /// <remarks/>
        NewZealand,
        
        /// <remarks/>
        Turkey,
        
        /// <remarks/>
        Botswana,
        
        /// <remarks/>
        Panama,
        
        /// <remarks/>
        CostaRica,
        
        /// <remarks/>
        Venezuela,
        
        /// <remarks/>
        DominicanRepublic,
        
        /// <remarks/>
        Ecuador,
        
        /// <remarks/>
        Guatemala,
        
        /// <remarks/>
        Peru,
        
        /// <remarks/>
        Honduras,
        
        /// <remarks/>
        TrinidadTobago,
        
        /// <remarks/>
        Australia,
        
        /// <remarks/>
        Jamaica,
        
        /// <remarks/>
        Bahamas,
        
        /// <remarks/>
        SaintKittsNevis,
        
        /// <remarks/>
        Barbados,
        
        /// <remarks/>
        Ghana,
        
        /// <remarks/>
        Spain,
        
        /// <remarks/>
        Portugal,
        
        /// <remarks/>
        Uruguay,
        
        /// <remarks/>
        Paraguay,
        
        /// <remarks/>
        HongKong,
        
        /// <remarks/>
        Bolivia,
        
        /// <remarks/>
        Nigeria,
        
        /// <remarks/>
        Bermuda,
        
        /// <remarks/>
        USVirginIslands,
        
        /// <remarks/>
        Nicaragua,
        
        /// <remarks/>
        ElSalvador,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class AddressWithName : Address {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string companyNameField;
        
        private string titleField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.alarm.com/WebServices")]
    public partial class AddressWithCoordinates : Address {
        
        private System.Nullable<double> latitudeField;
        
        private System.Nullable<double> longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<double> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<double> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateSerialNumber", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class ValidateSerialNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.alarm.com/WebServices")]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public string serialNumber;
        
        public ValidateSerialNumberRequest() {
        }
        
        public ValidateSerialNumberRequest(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string serialNumber) {
            this.Authentication = Authentication;
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateSerialNumberResponse", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class ValidateSerialNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.SerialNumberValidationResult ValidateSerialNumberResult;
        
        public ValidateSerialNumberResponse() {
        }
        
        public ValidateSerialNumberResponse(SOS.FOS.CellStation.AlarmComWebServiceValidate.SerialNumberValidationResult ValidateSerialNumberResult) {
            this.ValidateSerialNumberResult = ValidateSerialNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCoverage", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class CheckCoverageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.alarm.com/WebServices")]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=1)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.NetworkEnum network;
        
        public CheckCoverageRequest() {
        }
        
        public CheckCoverageRequest(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address, SOS.FOS.CellStation.AlarmComWebServiceValidate.NetworkEnum network) {
            this.Authentication = Authentication;
            this.address = address;
            this.network = network;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCoverageResponse", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class CheckCoverageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.CoverageResultEnum CheckCoverageResult;
        
        public CheckCoverageResponse() {
        }
        
        public CheckCoverageResponse(SOS.FOS.CellStation.AlarmComWebServiceValidate.CoverageResultEnum CheckCoverageResult) {
            this.CheckCoverageResult = CheckCoverageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckModemAndCoverage", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class CheckModemAndCoverageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.alarm.com/WebServices")]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public string modemSerialNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=1)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address;
        
        public CheckModemAndCoverageRequest() {
        }
        
        public CheckModemAndCoverageRequest(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string modemSerialNumber, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address) {
            this.Authentication = Authentication;
            this.modemSerialNumber = modemSerialNumber;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckModemAndCoverageResponse", WrapperNamespace="http://www.alarm.com/WebServices", IsWrapped=true)]
    public partial class CheckModemAndCoverageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.alarm.com/WebServices", Order=0)]
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.CombinedValidationResult CheckModemAndCoverageResult;
        
        public CheckModemAndCoverageResponse() {
        }
        
        public CheckModemAndCoverageResponse(SOS.FOS.CellStation.AlarmComWebServiceValidate.CombinedValidationResult CheckModemAndCoverageResult) {
            this.CheckModemAndCoverageResult = CheckModemAndCoverageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateSoapChannel : SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateSoapClient : System.ServiceModel.ClientBase<SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap>, SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap {
        
        public ValidateSoapClient() {
        }
        
        public ValidateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.ValidateSerialNumber(SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest request) {
            return base.Channel.ValidateSerialNumber(request);
        }
        
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.SerialNumberValidationResult ValidateSerialNumber(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string serialNumber) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest();
            inValue.Authentication = Authentication;
            inValue.serialNumber = serialNumber;
            SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse retVal = ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).ValidateSerialNumber(inValue);
            return retVal.ValidateSerialNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse> SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.ValidateSerialNumberAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest request) {
            return base.Channel.ValidateSerialNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberResponse> ValidateSerialNumberAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string serialNumber) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSerialNumberRequest();
            inValue.Authentication = Authentication;
            inValue.serialNumber = serialNumber;
            return ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).ValidateSerialNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.CheckCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest request) {
            return base.Channel.CheckCoverage(request);
        }
        
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.CoverageResultEnum CheckCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address, SOS.FOS.CellStation.AlarmComWebServiceValidate.NetworkEnum network) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest();
            inValue.Authentication = Authentication;
            inValue.address = address;
            inValue.network = network;
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse retVal = ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).CheckCoverage(inValue);
            return retVal.CheckCoverageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse> SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.CheckCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest request) {
            return base.Channel.CheckCoverageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageResponse> CheckCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address, SOS.FOS.CellStation.AlarmComWebServiceValidate.NetworkEnum network) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckCoverageRequest();
            inValue.Authentication = Authentication;
            inValue.address = address;
            inValue.network = network;
            return ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).CheckCoverageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.CheckModemAndCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest request) {
            return base.Channel.CheckModemAndCoverage(request);
        }
        
        public SOS.FOS.CellStation.AlarmComWebServiceValidate.CombinedValidationResult CheckModemAndCoverage(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string modemSerialNumber, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest();
            inValue.Authentication = Authentication;
            inValue.modemSerialNumber = modemSerialNumber;
            inValue.address = address;
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse retVal = ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).CheckModemAndCoverage(inValue);
            return retVal.CheckModemAndCoverageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse> SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap.CheckModemAndCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest request) {
            return base.Channel.CheckModemAndCoverageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageResponse> CheckModemAndCoverageAsync(SOS.FOS.CellStation.AlarmComWebServiceValidate.Authentication Authentication, string modemSerialNumber, SOS.FOS.CellStation.AlarmComWebServiceValidate.Address address) {
            SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest inValue = new SOS.FOS.CellStation.AlarmComWebServiceValidate.CheckModemAndCoverageRequest();
            inValue.Authentication = Authentication;
            inValue.modemSerialNumber = modemSerialNumber;
            inValue.address = address;
            return ((SOS.FOS.CellStation.AlarmComWebServiceValidate.ValidateSoap)(this)).CheckModemAndCoverageAsync(inValue);
        }
    }
}
